/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
      {type: 'autogenerated', dirName: '.'},
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        {
          type: 'link',
          label: 'Customizing the results with template overrides',
          href: 'https://blue-coder.com/help/blog/customizing-search-results'
        },
        {
          type: 'link',
          label: 'Customizing the results with YOOtheme Pro',
          href: 'https://blue-coder.com/help/blog/jfilters-yootheme-pro'
        },
        {
          type: 'link',
          label: 'Showing images in the results',
          href: 'https://blue-coder.com/help/blog/showing-images-in-the-search-results-in-joomla-4-1-and-above'
        },
        {
          type: 'link',
          label: 'Showing custom fields in the results',
          href: 'https://blue-coder.com/help/blog/adding-custom-fields-in-the-search-results'
        },
        {
          type: 'link',
          label: 'Using clickable custom fields and tags in your Joomla text',
          href: 'https://blue-coder.com/help/blog/using-clickable-custom-fields-and-tags-in-your-joomla-text'
        },
        {
          type: 'link',
          label: 'View more',
          href: 'https://blue-coder.com/help/blog'
        },
      ],
    }
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
